booksProject/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("",views.home_view,name="home"),
    path("book-detail/<int:id>/",views.book_detail,name="book-detail"),
    path("add-book/",views.add_book,name="add-book"),
    path('edit-book/<int:id>/', views.edit_book, name='edit-book'),
    path('delete-book/<int:id>/', views.delete_book, name='delete-book'),
    ]


booksProject/booksProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings


from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bookstore/",include("books.urls")),
]

# appending the urls with the static urls

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

booksProject/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    isbn = models.CharField(max_length=100)
    image = models.ImageField(null=False,blank=False,upload_to='images/')
    created_at = models.DateTimeField(auto_now=True,blank=True)
    
    
    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        ordering = ['-created_at']

booksProject/books/forms.py
from django.forms import ModelForm

from django import forms

from .models import Book


class EditBookForm(ModelForm):
    
    model = Book
    fields = '__all__'
    
    widgets = {
             'title': forms.TextInput(attrs={'class': 'form-control'}),
             'author': forms.TextInput(attrs={'class': 'form-control'}),
             'price': forms.TextInput(attrs={'class': 'form-control'}),
             'isbn': forms.TextInput(attrs={'class': 'form-control'}),
             'image': forms.TextInput(attrs={'class': 'form-control'}),
        }
    

booksProject/books/views.py
from django.shortcuts import render,redirect,get_object_or_404

from django.http import HttpResponse

from . models import Book

from .forms import EditBookForm

# Create your views here.

def home_view(request):
    books = Book.objects.all()
    context = {'books':books}
    return render(request,"books/home.html",context)





def add_book(request):
    if request.method == 'POST':
        data = request.POST
        image = request.FILES.get('image_file')
        #creating and saving the book
        book = Book.objects.create(
            title = data['title'],
            author = data['author'],
           isbn = data['isbn'],
           price = data['price'],
           image = image     
        )
        return redirect("books:home")
    return render(request,"books/add-book.html")



def book_detail(request,id):
    #book = Book.objects.get(id=id)
    book = get_object_or_404(Book, id=id)
    context = {'book':book}
    return render(request,"books/book-detail.html",context)
    


def edit_book(request,id):
    # getting the book with id to be updated
    book = Book.objects.get(id=id)
    # populating the form with the book's information
    form = EditBookForm(instance=book)
    
    if request.method == "POST":
        form = EditBookForm(request.POST,request.Files,instance=book)
          # checking if the form's data is valid
        if form.is_valid():
             # saving the data to the database
            form.save()
            return redirect("books:home")
    return render(request,"books/update-book.html",{'edit_form':form})
            
        




def delete_book(request,id):
    return HttpResponse("Book deleted")

booksProject/books/templates/books/add-book.html
{% extends 'books/base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-4">
        {% comment %} <a href="{% url 'books:home' %}" class="my-3 btn btn-dark btn-sm">Go Back</a> {% endcomment %}
        <div class="card shadow-lg">
            <div class="card-body">
                <!-- the form for adding a book -->
                <form method="POST" enctype="multipart/form-data" action="">
                    <!-- this is for securing the form from malicious attacks -->
                    {% csrf_token %}
                    <!-- this is the label and input for the Title -->
                    <div class="mb-3">
                        <label class="form-label font-weight-bold">Book Title</label>
                        <input required type="text" name="title" class="form-control" placeholder="Enter Book Title">
                    </div>
                    <!-- this is the label and input for the Author -->
                    <div class="mb-3">
                        <label class="form-label font-weight-bold">Author</label>
                        <input required type="text" name="author" class="form-control" placeholder="Book Author">
                    </div>
                    <!-- this is the label and input for the Price -->
                    <div class="mb-3">
                        <label class="form-label font-weight-bold">Price</label>
                        <input required type="text" name="price" class="form-control" placeholder="Price">
                    </div>
                    <!-- this is the label and input for the ISBN -->
                    <div class="mb-3">
                        <label class="form-label font-weight-bold">ISBN</label>
                        <input required type="text" name="isbn" class="form-control" placeholder="ISBN">
                    </div>
                    <!-- this is the label and input for the Image -->
                    <div class="mb-3">
                        <label class="form-label font-weight-bold">Upload Image:</label>
                        <input required type="file" name="image-file" class="form-control" id="customFile" />
                    </div>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-success btn-block mb-4">submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

booksProject/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Store</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% block content %}
        
    {% endblock %}
</body>
</html>

booksProject/books/templates/books/book-detail.html
{% extends 'books/base.html' %}

<!-- this will help render the images -->
{% load static %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <div class="">
            <a href = "{% url 'books:home' %}">Go Back</a>
        </div> 
        <div style="height: 90vh">   
            <h4>{{book.title}}</h4>
            <h4>{{book.author}}</h4>
            <small>ISBN : {{book.isbn}} </small><br>
            <small> Price : {{book.price}} </small><br>
            <img class="img-fluid text-center" style="max-width: 100%; max-height: 100%" src="/images/{{book.image}}" alt="book"/>
            <a href="{% url 'books:edit-book' book.id %}" class="btn btn-success btn-sm">Edit Book</a>
            <a href="{% url 'books:delete-book' book.id  %}" class="btn btn-success btn-sm">Delete Book</a>
        </div>
    </div>   
</div>
{% endblock %}

booksProject/books/templates/books/home.html
{% extends 'books/base.html' %}

<!-- this will help render the images -->
{% load static %}

{% block content %}
<div class="container mb-4">
    <div class="row">
        <!-- side navbar here -->
        <div class="col-md-3 mt-3">
            <div class="card">
                <h4 class="card-header px-3">Menu</h4>
                <ul class="list-group list-group-light list-group-small">
                    <li class="list-group-item px-3"><a href="{% url 'books:home' %}">Home</a></li>
                </ul>
                <a href="{% url 'books:add-book' %}" class="m-2 btn btn-dark btn-sm">Add Book</a>
            </div>
        </div>
        <!-- books here -->
        <div class="col-md-9 mt-3">
            <div class="row">
                <!-- using a for loop to loop through all the books -->
                {% for book in books %}
                <div class="col-md-4">
                    <div class="card my-2">
                        <a href="">
                            <!-- this is the book image -->
                            <img src="/images/{{book.image}}" class="card-img-top" style="height:250px" />
                        </a>
                        <div class="card-body">
                            <!-- this is the book title -->
                            <h4 class="card-text">{{ book.title }}</h4>
                        </div>
                        <a href="{% url 'books:book-detail' book.id %}" class="m-2 btn btn-outline-dark btn-sm">View Book</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

booksProject/books/templates/books/update-book.html
{% extends 'books/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <a href="{% url 'books:home' %}" class="my-3 btn btn-dark btn-sm">Go Back</a>
        <div class="card shadow-lg">
            <div class="card-body">
                <!-- the form for adding a book -->
                <form method="POST" enctype="multipart/form-data" action="">
                    <!-- this is for securing the form from malicious attacks -->
                    {% csrf_token %}
                    <p>{{ edit_form }}</p>
                    <!-- Submit button -->
                    <button type="submit" class="btn btn-success btn-block mb-4">Update Book</button>
                </form>
            </div>     
        </div>
    </div>
</div>
{% endblock %}